version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=faq_project.settings
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"